"""empty message

Revision ID: f53d55b38666
Revises: e2ddd01cdaff
Create Date: 2022-08-15 14:28:10.822983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53d55b38666'
down_revision = 'e2ddd01cdaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
